services:
  app:
    build: .
    container_name: transaction_app
    command: >
      sh -c "
      until pg_isready -h db -p 5432; do sleep 2; done &&
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  test:
    build: .
    container_name: transaction_tests
    command: >
      sh -c "
      until pg_isready -h test-db -p 5432; do sleep 2; done &&
      alembic -x db_url='postgresql+psycopg2://transaction_user:transaction_pass@test-db:5432/transaction_test_db' upgrade head &&
      pytest
      "
    volumes:
      - .:/code
    depends_on:
      - test-db
      - redis

  db:
    image: postgres:17-alpine
    container_name: transaction_db
    environment:
      POSTGRES_USER: transaction_user
      POSTGRES_PASSWORD: transaction_pass
      POSTGRES_DB: transaction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test-db:
    image: postgres:17-alpine
    container_name: transaction_test_db
    environment:
      POSTGRES_USER: transaction_user
      POSTGRES_PASSWORD: transaction_pass
      POSTGRES_DB: transaction_test_db
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:8-alpine
    container_name: transaction_redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: transaction_celery
    command: celery -A app.workers.celery_worker worker --loglevel=info
    volumes:
      - .:/code

    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  test_postgres_data:
