services:
  app:
    build: .
    container_name: transaction_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:17-alpine
    container_name: transaction_db
    environment:
      POSTGRES_USER: transaction_user
      POSTGRES_PASSWORD: transaction_pass
      POSTGRES_DB: transaction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:8-alpine
    container_name: transaction_redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: transaction_celery
    command: celery -A app.workers.celery_worker worker --loglevel=info
    volumes:
      - .:/code

    depends_on:
      - db
      - redis

volumes:
  postgres_data:
